apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: backends
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: backend-client
        image: 
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: backends
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100